name: flutter_base
description: Real Agent

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 0.5.0+50
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  flutter_inappwebview: ^5.4.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  image_gallery_saver: ^1.7.1
  #Bloc architecture
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.2
  hydrated_bloc: ^8.1.0
  equatable: ^2.0.3

  #Restful Api
  retrofit: ^3.0.1+1
  dio: ^4.0.6

  #router
  get: ^4.3.8
  fluro: ^2.0.3

  #Json Serialization
  json_annotation: ^4.4.0

  #Internationalization
  intl: ^0.17.0
  tiengviet: ^0.5.0

  #Local Storage
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2

  #Firebase
  firebase_core: ^2.3.0

  #Geolocator
  geolocator: ^8.2.1

  #Cached image network
  cached_network_image: ^3.2.0

  #Image picker
  image_picker: ^0.8.5
  image_cropper: ^2.0.3

  #Permission
  permission_handler: ^9.2.0

  #url_launcher
  url_launcher: ^6.1.0
  flutter_phone_direct_caller: ^2.1.1

  #Shimmer
  shimmer: ^2.0.0

  flutter_switch: ^0.3.2
  # Share
  share_plus: ^4.0.4
  #uid
  uuid: ^3.0.5

  #OneSignal Service
  onesignal_flutter: ^3.3.2
  native_flutter_proxy: ^0.1.15
  #Webview
  webview_flutter: ^3.0.4
  flutter_html: ^3.0.0-alpha.5

  #carousel_slider
  carousel_slider: ^4.0.0

  table_calendar: ^3.0.6

  #Connectivity
  connectivity_plus: ^2.3.0
  overlay_support: ^1.2.1
  #flushbar
  intl_utils: ^2.6.1
  pin_code_fields: ^7.3.0
  scroll_to_index: ^2.1.1
  build_resolvers: ^2.0.4

  fluttertoast: ^8.0.9
  syncfusion_flutter_datepicker: ^19.3.57
  syncfusion_localizations: ^19.3.57
  another_flushbar: ^1.10.29
  
  gallery_saver: ^2.3.2
  uni_links: ^0.5.1
  expandable: ^5.0.1
  package_info_plus: ^1.4.2
  flutter_launcher_icons: ^0.10.0

  font_awesome_flutter: ^10.2.1

  connectivity: ^3.0.6
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

dependency_overrides:
  another_flushbar: 1.10.28

flutter:
  generate: true

  uses-material-design: true

  assets:
    # Json file
    - assets/images/
    # Common images

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
#flutter_intl:
#  enabled: true
#  arb_dir: lib/app/language/l10n
#  output_dir: lib/app/language/generated
